# Generated by Django 4.2.7 on 2023-11-13 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taverne', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='race',
            new_name='titre',
        ),
        migrations.RemoveField(
            model_name='character',
            name='type',
        ),
    ]
